### ISSUE TITLE
[피드백] 배고프다.. 맛있는.. 음식들..

### ISSUE THREAD

**Issue by cbj0010** [woorifisa-service-dev-3rd/frontend-1st-ppl#19]
1. 소개와 영업시간 사이에 여백을 조금 더 주면 시각적으로 더 편할 거 같아요!
2. 정렬기능 있으면 좋을 거 같아요 ex) 좋아요가 많은걸 먼저 볼 수 있도록 선택하는거 같은 필터 기능이 있으면 좋을거 같습니다.
3. 카페, 한식, 치킨,닭강정과 같은 제목 앞에 귀여운 아이콘이 들어가면 더 귀여울거 같아요 😉

맛있는 음식추천 감사합니다! 고생하셨습니다~

**Comment by dlaudfuf33** [comment]
2번 : js 추가 이후 구현예정입니다 :)
3번 : 카테고리별 아이콘 고려해보겠습니다.
피드백 감사합니다.
