### ISSUE TITLE
smile :D team review

### ISSUE THREAD

**Issue by bw02184** [woorifisa-service-dev-3rd/frontend-1st-ppl#20]
1. 찜 목록으로 랜덤 돌리는 기능 좋은 것 같습니다!
찜 목록을 확인하는 아이콘이 장바구니 아이콘 보다는 조금 더 찜 목록을 연상 시키는 아이콘을 사용하면 좋을 것 같습니다!

2. 찜 목록에서 랜덤을 돌릴 때 음식종류별로 랜덤을 돌리는 기능이 있으면 좋을 것 같습니다.
3. 잘 만드셨네요~! 장바구니 -> 이런 식으로 하트 밑에 몇 개의 식당을 찜했는지 뜨면 더 직관적으로 서비스를 이해할 수 있을 것 같아요!
![image](https://github.com/user-attachments/assets/e132c56e-f409-4953-9823-e2fe891e3f5c)

**Comment by dlaudfuf33** [comment]
피드백 감사합니다! 
3번 의견 적극 수용하겠습니다.

**Comment by dlaudfuf33** [comment]
피드백 감사합니다!
3번 의견 적극 수용하겠습니다.
