### ISSUE TITLE
triple-roulette-review

### ISSUE THREAD

**Issue by qbobl5** [woorifisa-service-dev-3rd/frontend-1st-ppl#21]
1. 나중에 정렬 기능 추가되면 보기 편할 것 같습니다.
2. 카테고리 (한식, 카페 등) 누르면 카테고리 목록으로 이동할 수 있으면 더 좋을 것 같습니다.
(옆에 더보기 옵션 추가 되어도 좋을 것 같아요!)

**Comment by jyp-on** [comment]
특정 카테고리로 이동하는 기능 좋은 것 같습니다.
추후 반영해보도록 하겠습니다!
