### ISSUE TITLE
점심메뉴 결정 완. (몇가지 제안사항)

### ISSUE THREAD

**Issue by Kong-E** [woorifisa-service-dev-3rd/frontend-1st-ppl#23]
1. 식당이름을 눌러도 네이버 지도로 이동되었으면 좋겠어요!
2. 네이버 지도로 이동될 때 새창에서 열린다면 사용자 입장에서 더 좋을 것 같아요~ (blank 속성)
3. 식당 추가 (제안) 기능도 제안해봅니다~

**Comment by dlaudfuf33** [comment]
피드백 감사합니다.
조금 더 페이지 이동 편의성 고려해보겠습니다.
3번의견은 범위를 식당의 넓히게되면 고려해보겠습니다!
