### ISSUE TITLE
잘 봤습니다! 질문 있습니다.

### ISSUE THREAD

**Issue by jabin1221** [woorifisa-service-dev-3rd/frontend-1st-ppl#24]
1. 추후에 DB와 같은 다양한 기술들을 학습한 뒤, 평점 순 혹은 조회 순 정렬 같은 기능을 추가할 계획이 있으신가요?
2. 각 카드들의 사진이 찌그러져 보이는 경우가 있는 것 같습니다.

**Comment by jyp-on** [comment]
1. 백엔드 적용까지는 생각하지 않은 프로젝트라서 해당 기능은 계획 된 바가 없습니다!
2. 감사합니다. 추후 반영해보록 하겠씁니다.
