### ISSUE TITLE
맛있는 음식점을 추천 감사합니다 6개월간 잘 쓸 수 있을 것 같아요! (질문 있습니다.)

### ISSUE THREAD

**Issue by my123dsa** [woorifisa-service-dev-3rd/frontend-1st-ppl#25]
1. 이미지를 누르면 지도로 이동한다는 정보가 있으면 좋을 것 같아요! 
어디로 이어지는지 상세정보가 뜨면 좋을 것 같습니다.
 ex) 클릭시 지도로 이동합니다!

2. 찜하기 버튼 클릭할 때 애니메이션 효과가 클릭을 하고 있는 시간 
짧게, 또는 길게에 따라 보이는 것이 다르게 보이는데, 짧게 클릭해도 애니메이션이 길게 보일 수 있으면 좋을 것 같습니다.

3. 찜하기 버튼을 누르고 나면 다른 찜하기 버튼들과 달라 장바구니로 직접가서 확인해야할 것 같은데 찜하기 버튼을 누르면 이모티콘이 soild로 변하여 페이지 내에서 확인할 수 있으면 더 좋을 것 같아요!

**Comment by dlaudfuf33** [comment]
피드백 감사합니다.
1번 의견 : 수용하겠습니다
2번 의견 : 길게 눌렀을때에 시각적 차이가 있었으면 하는 의도로 하였으나 수정해도록하겠습니다.
