### ISSUE TITLE
[강김길] 오늘의 점메추는 ? ㅎㅎ

### ISSUE THREAD

**Issue by rlfrkdms1** [woorifisa-service-dev-3rd/frontend-1st-ppl#26]
잘 봤습니다 !
- 창이 작아질 시에 card안에 있는 글자들이 잘리는데 고려해보시면 좋을 것 같습니다 !
- 식당이름이 `가마로강정 상암점`라면 `가마로강정_상암점`처럼 언더바를 넣으셨는데, 의도하신건지 의미가 있는것인지 궁금합니다 !

**Comment by dlaudfuf33** [comment]
피드백 감사합니다.
이미지 파일명과 맞추려다 보니 _ 언더바를 사용하게 되었습니다!
