### ISSUE TITLE
피드백:)

### ISSUE THREAD

**Issue by kh-0818** [woorifisa-service-dev-3rd/frontend-1st-ppl#27]
유익한 정보들인 것 같아서 잘 봤습니다!! 
호버 사용해서 링크(?)를 알아볼 수 있게 한 것을 인상깊게 봤고 로고 너무 귀여운 것 같아요!  다만 매장명이 길 때 텍스트가 잘리는 부분 체크해주시면 좋을 것 같구 기능 관련은 아니지만 내용이 점메추라는 단어와 완전히 일치하진 않는 것 같다는 생각이 듭니다,,,! 고생하셨어요~

**Comment by jyp-on** [comment]
피드백 감사합니다!
