### ISSUE TITLE
lunch-game-review

### ISSUE THREAD

**Issue by yaejinkong** [woorifisa-service-dev-3rd/frontend-1st-ppl#28]
너무 수고하셨습니다!
점심 먹기 전에 이용해보고 싶은 마음이 뿜뿜 하네요 ㅎ ㅎ

1. 클릭시 이동해요 버튼을 눌렀을 때 페이지 내에서 이동하는 것보다는 새로운 페이지로 이동되어 해당 지도를 보여주는 게 어떨까 싶습니다!
2.  명동 칼국수랑 청진생대구탕은 한식 카테고리로 넣는게 어떨까요 ? 카테고리별 식당을 잘 구분해서 서비스를 제공해주신다면 사용하기 편할 거 같아용!

**Comment by jyp-on** [comment]
좋은 피드백 감사합니다!!
